package schema

const API_BASE = "https://open.didiyunapi.com/dicloud"

const GET_RESULT_JOB_URL = API_BASE + "/i/result"
const LIST_REGION_URL = API_BASE + "/i/region/list"

const GET_DC2_URL = API_BASE + "/i/compute/dc2"
const LIST_DC2_URL = API_BASE + "/i/compute/dc2/list"
const COUNT_DC2_URL = API_BASE + "/i/compute/dc2/count"
const CREATE_DC2_URL = API_BASE + "/i/compute/dc2/assign"
const DELETE_DC2_URL = API_BASE + "/i/compute/dc2/delete"
const START_DC2_URL = API_BASE + "/i/compute/dc2/start"
const STOP_DC2_URL = API_BASE + "/i/compute/dc2/stop"
const REBOOT_DC2_URL = API_BASE + "/i/compute/dc2/reboot"
const REINSTALL_DC2_URL = API_BASE + "/i/compute/dc2/reinstall"
const CHANGE_PASSWORD_DC2_URL = API_BASE + "/i/compute/dc2/changePassword"
const CHANGE_NAME_DC2_URL = API_BASE + "/i/compute/dc2/changeName"
const CHANGE_SPEC_DC2_URL = API_BASE + "/i/compute/dc2/changeSpec"

const LIST_IMAGE_URL = API_BASE + "/i/image/list"

const LIST_SSHKEY_URL = API_BASE + "/i/sshkeys/list"
const CREATE_SSHKEY_URL = API_BASE + "/i/sshkeys/create"
const DELETE_SSHKEY_URL = API_BASE + "/i/sshkeys/delete"

const GET_EIP_URL = API_BASE + "/i/network/eip"
const LIST_EIP_URL = API_BASE + "/i/network/eip/list"
const COUNT_EIP_URL = API_BASE + "/i/network/eip/count"
const CREATE_EIP_URL = API_BASE + "/i/network/eip/assign"
const ATTACH_EIP_URL = API_BASE + "/i/network/eip/attach"
const DEATCH_EIP_URL = API_BASE + "/i/network/eip/deatch"
const DELETE_EIP_URL = API_BASE + "/i/network/eip/delete"
const CHANGE_BANDWIDTH_EIP_URL = API_BASE + "/i/network/eip/changeBandwidth"

const GET_EBS_URL = API_BASE + "/i/storage/ebs"
const LIST_EBS_URL = API_BASE + "/i/storage/ebs/list"
const COUNT_EBS_URL = API_BASE + "/i/storage/ebs/count"
const CREATE_EBS_URL = API_BASE + "/i/storage/ebs/assign"
const DELETE_EBS_URL = API_BASE + "/i/storage/ebs/delete"
const ATTACH_EBS_URL = API_BASE + "/i/storage/ebs/attach"
const DEATCH_EBS_URL = API_BASE + "/i/storage/ebs/deatch"
const CHANGE_NAME_EBS_URL = API_BASE + "/i/storage/ebs/changeName"
const CHANGE_SIZE_EBS_URL = API_BASE + "/i/storage/ebs/changeSize"

const LIST_SNAP_URL = API_BASE + "/i/storage/snapshot/list"
const COUNT_SNAP_URL = API_BASE + "/i/storage/snapshot/count"
const CREATE_SNAP_URL = API_BASE + "/i/storage/snapshot/assign"
const DELETE_SNAP_URL = API_BASE + "/i/storage/snapshot/delete"
const REVERT_SNAP_URL = API_BASE + "/i/storage/snapshot/revert"
const CHANGE_NAME_SNAP_URL = API_BASE + "/i/storage/snapshot/changeName"

const GET_VPC_URL = API_BASE + "/i/network/vpc"
const LIST_VPC_URL = API_BASE + "/i/network/vpc/list"
const COUNT_VPC_URL = API_BASE + "/i/network/vpc/count"
const CREATE_VPC_URL = API_BASE + "/i/network/vpc/assign"
const DELETE_VPC_URL = API_BASE + "/i/network/vpc/delete"
const CHANGE_NAME_VPC_URL = API_BASE + "/i/network/vpc/changeName"
const CIDR_VPC_URL = API_BASE + "/i/network/vpc/cidr"
const GET_SUBNET_VPC_URL = API_BASE + "/i/network/vpc/subnet"
const LIST_SUBNET_VPC_URL = API_BASE + "/i/network/vpc/subnet/list"
const CREATE_SUBNET_VPC_URL = API_BASE + "/i/network/vpc/subnet/create"
const COUNT_SUBNET_VPC_URL = API_BASE + "/i/network/vpc/subnet/count"
const DELETE_SUBNET_VPC_URL = API_BASE + "/i/network/vpc/subnet/delete"
const CHANGE_NAME_SUBNET_VPC_URL = API_BASE + "/i/network/vpc/subnet/changeName"
const CHECK_SUBNET_VPC_URL = API_BASE + "/i/network/vpc/subnet/checkCidrOverlap"

const LIST_SG_URL = API_BASE + "/i/network/sg/list"
const COUNT_SG_URL = API_BASE + "/i/network/sg/count"
const CREATE_SG_URL = API_BASE + "/i/network/sg/assign"
const DELETE_SG_URL = API_BASE + "/i/network/sg/delete"
const CHANGE_NAME_SG_URL = API_BASE + "/i/network/sg/changeName"
const ATTACH_SG_URL = API_BASE + "/i/network/sg/attach"
const DEATCH_SG_URL = API_BASE + "/i/network/sg/detach"
const LIST_SG_RULE_URL = API_BASE + "/i/network/sg/rule/list"
const COUNT_SG_RULE_URL = API_BASE + "/i/network/sg/rule/count"
const CREATE_SG_RULE_URL = API_BASE + "/i/network/sg/rule/assign"
const DELETE_SG_RULE_URL = API_BASE + "/i/network/sg/rule/delete"

const CREATE_SLB_URL = API_BASE + "/i/network/slb/create"
const DELETE_SLB_URL = API_BASE + "/i/network/slb/delete"
const CHANGE_NAME_SLB_URL = API_BASE + "/i/network/slb/changeName"
const LIST_LISTENER_MEMBER_SLB_URL = API_BASE + "/i/network/slb/listener/pool/member/list"
const CREATE_LISTENER_MEMBER_SLB_URL = API_BASE + "/i/network/slb/listener/pool/member/create"
const UPDATE_LISTENER_MEMBER_SLB_URL = API_BASE + "/i/network/slb/listener/pool/member/update"
const DELETE_LISTENER_MEMBER_SLB_URL = API_BASE + "/i/network/slb/listener/pool/member/delete"
const LIST_LISTENER_SLB_URL = API_BASE + "/i/network/slb/listener/list"
const CREATE_LISTENER_SLB_URL = API_BASE + "/i/network/slb/listener/create"
const UPDATE_LISTENER_SLB_URL = API_BASE + "/i/network/slb/listener/update"
const DELETE_LISTENER_SLB_URL = API_BASE + "/i/network/slb/listener/delete"
const GET_SLB_URL = API_BASE + "/i/network/slb"
const COUNT_SLB_URL = API_BASE + "/i/network/slb/count"
const LIST_SLB_URL = API_BASE + "/i/network/slb/list"
const LIST_ALGORITHM_SLB_URL = API_BASE + "/i/network/slb/algorithm"

const GET_MONITOR_COUNTER = API_BASE + "/m/api/counter"
const GET_MONITOR_DATA = API_BASE + "/m/api/data"
